"""add_campus_card_and_pending_action_tables

Revision ID: 109770f6537c
Revises: 9084e53aa354
Create Date: 2026-03-10 16:02:23.568886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109770f6537c'
down_revision: Union[str, None] = '9084e53aa354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campus_card_accounts_card_no_key', 'campus_card_accounts', type_='unique')
    op.drop_constraint('campus_card_accounts_user_id_key', 'campus_card_accounts', type_='unique')
    op.create_index(op.f('ix_campus_card_accounts_card_no'), 'campus_card_accounts', ['card_no'], unique=True)
    op.create_index(op.f('ix_campus_card_accounts_status'), 'campus_card_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_campus_card_accounts_user_id'), 'campus_card_accounts', ['user_id'], unique=True)
    op.drop_constraint('campus_card_accounts_user_id_fkey', 'campus_card_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'campus_card_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_campus_card_transactions_txn_type'), 'campus_card_transactions', ['txn_type'], unique=False)
    op.drop_constraint('campus_card_transactions_account_id_fkey', 'campus_card_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'campus_card_transactions', 'campus_card_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pending_actions_action_type'), 'pending_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_pending_actions_status'), 'pending_actions', ['status'], unique=False)
    op.drop_constraint('pending_actions_session_id_fkey', 'pending_actions', type_='foreignkey')
    op.drop_constraint('pending_actions_user_id_fkey', 'pending_actions', type_='foreignkey')
    op.create_foreign_key(None, 'pending_actions', 'agent_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pending_actions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_actions', type_='foreignkey')
    op.drop_constraint(None, 'pending_actions', type_='foreignkey')
    op.create_foreign_key('pending_actions_user_id_fkey', 'pending_actions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('pending_actions_session_id_fkey', 'pending_actions', 'agent_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_pending_actions_status'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_action_type'), table_name='pending_actions')
    op.drop_constraint(None, 'campus_card_transactions', type_='foreignkey')
    op.create_foreign_key('campus_card_transactions_account_id_fkey', 'campus_card_transactions', 'campus_card_accounts', ['account_id'], ['id'])
    op.drop_index(op.f('ix_campus_card_transactions_txn_type'), table_name='campus_card_transactions')
    op.drop_constraint(None, 'campus_card_accounts', type_='foreignkey')
    op.create_foreign_key('campus_card_accounts_user_id_fkey', 'campus_card_accounts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_campus_card_accounts_user_id'), table_name='campus_card_accounts')
    op.drop_index(op.f('ix_campus_card_accounts_status'), table_name='campus_card_accounts')
    op.drop_index(op.f('ix_campus_card_accounts_card_no'), table_name='campus_card_accounts')
    op.create_unique_constraint('campus_card_accounts_user_id_key', 'campus_card_accounts', ['user_id'])
    op.create_unique_constraint('campus_card_accounts_card_no_key', 'campus_card_accounts', ['card_no'])
    # ### end Alembic commands ###
