"""add_course_planning_tables

Revision ID: 25b4f539c6d1
Revises: c51ad01cad88
Create Date: 2026-03-16 16:41:48.592099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25b4f539c6d1'
down_revision: Union[str, None] = 'c51ad01cad88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_enrollment_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_enrollment_requests_request_type'), 'course_enrollment_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_course_enrollment_requests_semester'), 'course_enrollment_requests', ['semester'], unique=False)
    op.create_index(op.f('ix_course_enrollment_requests_status'), 'course_enrollment_requests', ['status'], unique=False)
    op.create_index(op.f('ix_course_enrollment_requests_user_id'), 'course_enrollment_requests', ['user_id'], unique=False)
    op.create_table('student_course_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('target_semester', sa.String(length=50), nullable=False),
    sa.Column('max_credits', sa.Integer(), nullable=False),
    sa.Column('preferred_days_json', sa.JSON(), nullable=True),
    sa.Column('avoid_days_json', sa.JSON(), nullable=True),
    sa.Column('avoid_morning', sa.Boolean(), nullable=False),
    sa.Column('avoid_evening', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_course_plans_status'), 'student_course_plans', ['status'], unique=False)
    op.create_index(op.f('ix_student_course_plans_target_semester'), 'student_course_plans', ['target_semester'], unique=False)
    op.create_index(op.f('ix_student_course_plans_user_id'), 'student_course_plans', ['user_id'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_course_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_prerequisites_course_id'), 'course_prerequisites', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_prerequisites_prerequisite_course_id'), 'course_prerequisites', ['prerequisite_course_id'], unique=False)
    op.create_index(op.f('ix_course_prerequisites_rule_type'), 'course_prerequisites', ['rule_type'], unique=False)
    op.create_table('course_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('section_code', sa.String(length=50), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('classroom', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('enrolled_count', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_sections_course_id'), 'course_sections', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_sections_section_code'), 'course_sections', ['section_code'], unique=False)
    op.create_index(op.f('ix_course_sections_semester'), 'course_sections', ['semester'], unique=False)
    op.create_index(op.f('ix_course_sections_status'), 'course_sections', ['status'], unique=False)
    op.create_index(op.f('ix_course_sections_weekday'), 'course_sections', ['weekday'], unique=False)
    op.create_table('student_completed_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_completed_courses_course_id'), 'student_completed_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_completed_courses_passed'), 'student_completed_courses', ['passed'], unique=False)
    op.create_index(op.f('ix_student_completed_courses_user_id'), 'student_completed_courses', ['user_id'], unique=False)
    op.create_table('course_enrollment_request_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['course_enrollment_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_enrollment_request_items_course_id'), 'course_enrollment_request_items', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollment_request_items_request_id'), 'course_enrollment_request_items', ['request_id'], unique=False)
    op.create_index(op.f('ix_course_enrollment_request_items_section_id'), 'course_enrollment_request_items', ['section_id'], unique=False)
    op.create_index(op.f('ix_course_enrollment_request_items_status'), 'course_enrollment_request_items', ['status'], unique=False)
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.add_column('courses', sa.Column('capacity', sa.Integer(), nullable=False,server_default='0'))
    op.add_column('courses', sa.Column('enrolled_count', sa.Integer(), nullable=False,server_default='0'))
    op.add_column('courses', sa.Column('course_type', sa.String(length=30), nullable=False,server_default='0'))
    op.add_column('courses', sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False,server_default='0'))
    op.add_column('courses', sa.Column('is_required', sa.Boolean(), nullable=False,server_default='0'))
    op.add_column('courses', sa.Column('offering_department', sa.String(length=100), nullable=True,server_default='0'))
    op.create_index(op.f('ix_courses_course_type'), 'courses', ['course_type'], unique=False)
    op.create_index(op.f('ix_courses_is_required'), 'courses', ['is_required'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_is_required'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_type'), table_name='courses')
    op.drop_column('courses', 'offering_department')
    op.drop_column('courses', 'is_required')
    op.drop_column('courses', 'weight')
    op.drop_column('courses', 'course_type')
    op.drop_column('courses', 'enrolled_count')
    op.drop_column('courses', 'capacity')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_course_enrollment_request_items_status'), table_name='course_enrollment_request_items')
    op.drop_index(op.f('ix_course_enrollment_request_items_section_id'), table_name='course_enrollment_request_items')
    op.drop_index(op.f('ix_course_enrollment_request_items_request_id'), table_name='course_enrollment_request_items')
    op.drop_index(op.f('ix_course_enrollment_request_items_course_id'), table_name='course_enrollment_request_items')
    op.drop_table('course_enrollment_request_items')
    op.drop_index(op.f('ix_student_completed_courses_user_id'), table_name='student_completed_courses')
    op.drop_index(op.f('ix_student_completed_courses_passed'), table_name='student_completed_courses')
    op.drop_index(op.f('ix_student_completed_courses_course_id'), table_name='student_completed_courses')
    op.drop_table('student_completed_courses')
    op.drop_index(op.f('ix_course_sections_weekday'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_status'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_semester'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_section_code'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_course_id'), table_name='course_sections')
    op.drop_table('course_sections')
    op.drop_index(op.f('ix_course_prerequisites_rule_type'), table_name='course_prerequisites')
    op.drop_index(op.f('ix_course_prerequisites_prerequisite_course_id'), table_name='course_prerequisites')
    op.drop_index(op.f('ix_course_prerequisites_course_id'), table_name='course_prerequisites')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_student_course_plans_user_id'), table_name='student_course_plans')
    op.drop_index(op.f('ix_student_course_plans_target_semester'), table_name='student_course_plans')
    op.drop_index(op.f('ix_student_course_plans_status'), table_name='student_course_plans')
    op.drop_table('student_course_plans')
    op.drop_index(op.f('ix_course_enrollment_requests_user_id'), table_name='course_enrollment_requests')
    op.drop_index(op.f('ix_course_enrollment_requests_status'), table_name='course_enrollment_requests')
    op.drop_index(op.f('ix_course_enrollment_requests_semester'), table_name='course_enrollment_requests')
    op.drop_index(op.f('ix_course_enrollment_requests_request_type'), table_name='course_enrollment_requests')
    op.drop_table('course_enrollment_requests')
    # ### end Alembic commands ###
