"""add_audit_and_tool_execution_logs

Revision ID: 4604e1cd6173
Revises: 71ea265b91d6
Create Date: 2026-03-10 17:12:05.536629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4604e1cd6173'
down_revision: Union[str, None] = '71ea265b91d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tool_execution_logs_status'), 'tool_execution_logs', ['status'], unique=False)
    op.create_index(op.f('ix_tool_execution_logs_tool_name'), 'tool_execution_logs', ['tool_name'], unique=False)
    op.drop_constraint('tool_execution_logs_session_id_fkey', 'tool_execution_logs', type_='foreignkey')
    op.create_foreign_key(None, 'tool_execution_logs', 'agent_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_execution_logs', type_='foreignkey')
    op.create_foreign_key('tool_execution_logs_session_id_fkey', 'tool_execution_logs', 'agent_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_tool_execution_logs_tool_name'), table_name='tool_execution_logs')
    op.drop_index(op.f('ix_tool_execution_logs_status'), table_name='tool_execution_logs')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    # ### end Alembic commands ###
