"""add_leave_tables

Revision ID: 71ea265b91d6
Revises: 109770f6537c
Create Date: 2026-03-10 16:44:18.038145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ea265b91d6'
down_revision: Union[str, None] = '109770f6537c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_approval_records_action'), 'approval_records', ['action'], unique=False)
    op.create_index(op.f('ix_approval_records_approver_id'), 'approval_records', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approval_records_leave_request_id'), 'approval_records', ['leave_request_id'], unique=False)
    op.drop_constraint('approval_records_approver_id_fkey', 'approval_records', type_='foreignkey')
    op.drop_constraint('approval_records_leave_request_id_fkey', 'approval_records', type_='foreignkey')
    op.create_foreign_key(None, 'approval_records', 'users', ['approver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'approval_records', 'leave_requests', ['leave_request_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leave_requests_end_date'), 'leave_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_type'), 'leave_requests', ['leave_type'], unique=False)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.drop_constraint('leave_requests_user_id_fkey', 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key('leave_requests_user_id_fkey', 'leave_requests', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_type'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_end_date'), table_name='leave_requests')
    op.drop_constraint(None, 'approval_records', type_='foreignkey')
    op.drop_constraint(None, 'approval_records', type_='foreignkey')
    op.create_foreign_key('approval_records_leave_request_id_fkey', 'approval_records', 'leave_requests', ['leave_request_id'], ['id'])
    op.create_foreign_key('approval_records_approver_id_fkey', 'approval_records', 'users', ['approver_id'], ['id'])
    op.drop_index(op.f('ix_approval_records_leave_request_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_approver_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_action'), table_name='approval_records')
    # ### end Alembic commands ###
