"""add capability self iter

Revision ID: 72e952057a76
Revises: 05b6541dc09b
Create Date: 2026-04-14 17:12:20.972987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e952057a76'
down_revision: Union[str, None] = '05b6541dc09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_spec_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('capability_name', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('artifact_type', sa.String(length=30), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['capability_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_spec_artifacts_artifact_type'), 'tool_spec_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_tool_spec_artifacts_capability_name'), 'tool_spec_artifacts', ['capability_name'], unique=False)
    op.create_index(op.f('ix_tool_spec_artifacts_proposal_id'), 'tool_spec_artifacts', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_tool_spec_artifacts_status'), 'tool_spec_artifacts', ['status'], unique=False)
    op.create_index(op.f('ix_tool_spec_artifacts_tool_name'), 'tool_spec_artifacts', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_spec_artifacts_tool_name'), table_name='tool_spec_artifacts')
    op.drop_index(op.f('ix_tool_spec_artifacts_status'), table_name='tool_spec_artifacts')
    op.drop_index(op.f('ix_tool_spec_artifacts_proposal_id'), table_name='tool_spec_artifacts')
    op.drop_index(op.f('ix_tool_spec_artifacts_capability_name'), table_name='tool_spec_artifacts')
    op.drop_index(op.f('ix_tool_spec_artifacts_artifact_type'), table_name='tool_spec_artifacts')
    op.drop_table('tool_spec_artifacts')
    # ### end Alembic commands ###
