"""add_more_database

Revision ID: 73e397c7306c
Revises: 112baf081407
Create Date: 2026-04-15 21:47:53.435035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e397c7306c'
down_revision: Union[str, None] = '112baf081407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canteens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canteen_code', sa.String(length=50), nullable=False),
    sa.Column('canteen_name', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('open_hours', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canteens_campus'), 'canteens', ['campus'], unique=False)
    op.create_index(op.f('ix_canteens_canteen_code'), 'canteens', ['canteen_code'], unique=True)
    op.create_index(op.f('ix_canteens_status'), 'canteens', ['status'], unique=False)
    op.create_table('dorm_buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_code', sa.String(length=50), nullable=False),
    sa.Column('building_name', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('gender_rule', sa.String(length=20), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dorm_buildings_building_code'), 'dorm_buildings', ['building_code'], unique=True)
    op.create_index(op.f('ix_dorm_buildings_campus'), 'dorm_buildings', ['campus'], unique=False)
    op.create_index(op.f('ix_dorm_buildings_gender_rule'), 'dorm_buildings', ['gender_rule'], unique=False)
    op.create_index(op.f('ix_dorm_buildings_status'), 'dorm_buildings', ['status'], unique=False)
    op.create_table('graduation_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_code', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('requirement_name', sa.String(length=100), nullable=False),
    sa.Column('requirement_type', sa.String(length=30), nullable=False),
    sa.Column('min_credits', sa.Integer(), nullable=False),
    sa.Column('min_course_count', sa.Integer(), nullable=False),
    sa.Column('rule_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department', 'major', 'grade', 'requirement_code', name='uq_graduation_requirements_program_rule')
    )
    op.create_index(op.f('ix_graduation_requirements_department'), 'graduation_requirements', ['department'], unique=False)
    op.create_index(op.f('ix_graduation_requirements_grade'), 'graduation_requirements', ['grade'], unique=False)
    op.create_index(op.f('ix_graduation_requirements_major'), 'graduation_requirements', ['major'], unique=False)
    op.create_index(op.f('ix_graduation_requirements_requirement_code'), 'graduation_requirements', ['requirement_code'], unique=False)
    op.create_index(op.f('ix_graduation_requirements_requirement_type'), 'graduation_requirements', ['requirement_type'], unique=False)
    op.create_index(op.f('ix_graduation_requirements_status'), 'graduation_requirements', ['status'], unique=False)
    op.create_table('shuttle_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_code', sa.String(length=50), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=100), nullable=True),
    sa.Column('start_campus', sa.String(length=100), nullable=True),
    sa.Column('end_campus', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_routes_end_campus'), 'shuttle_routes', ['end_campus'], unique=False)
    op.create_index(op.f('ix_shuttle_routes_route_code'), 'shuttle_routes', ['route_code'], unique=True)
    op.create_index(op.f('ix_shuttle_routes_start_campus'), 'shuttle_routes', ['start_campus'], unique=False)
    op.create_index(op.f('ix_shuttle_routes_status'), 'shuttle_routes', ['status'], unique=False)
    op.create_table('shuttle_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stop_code', sa.String(length=50), nullable=False),
    sa.Column('stop_name', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=True),
    sa.Column('location_desc', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_stops_campus'), 'shuttle_stops', ['campus'], unique=False)
    op.create_index(op.f('ix_shuttle_stops_status'), 'shuttle_stops', ['status'], unique=False)
    op.create_index(op.f('ix_shuttle_stops_stop_code'), 'shuttle_stops', ['stop_code'], unique=True)
    op.create_index(op.f('ix_shuttle_stops_stop_name'), 'shuttle_stops', ['stop_name'], unique=False)
    op.create_table('canteen_stalls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canteen_id', sa.Integer(), nullable=False),
    sa.Column('stall_code', sa.String(length=50), nullable=False),
    sa.Column('stall_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('floor_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canteen_id'], ['canteens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canteen_id', 'stall_code', name='uq_canteen_stalls_canteen_id_stall_code')
    )
    op.create_index(op.f('ix_canteen_stalls_canteen_id'), 'canteen_stalls', ['canteen_id'], unique=False)
    op.create_index(op.f('ix_canteen_stalls_category'), 'canteen_stalls', ['category'], unique=False)
    op.create_index(op.f('ix_canteen_stalls_stall_code'), 'canteen_stalls', ['stall_code'], unique=False)
    op.create_index(op.f('ix_canteen_stalls_status'), 'canteen_stalls', ['status'], unique=False)
    op.create_table('dorm_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(length=20), nullable=False),
    sa.Column('floor_no', sa.Integer(), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=False),
    sa.Column('occupied_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['dorm_buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'room_no', name='uq_dorm_rooms_building_id_room_no')
    )
    op.create_index(op.f('ix_dorm_rooms_building_id'), 'dorm_rooms', ['building_id'], unique=False)
    op.create_index(op.f('ix_dorm_rooms_room_no'), 'dorm_rooms', ['room_no'], unique=False)
    op.create_index(op.f('ix_dorm_rooms_status'), 'dorm_rooms', ['status'], unique=False)
    op.create_table('shuttle_route_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('travel_minutes_from_origin', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['shuttle_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['shuttle_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_id', name='uq_shuttle_route_stops_route_id_stop_id'),
    sa.UniqueConstraint('route_id', 'stop_order', name='uq_shuttle_route_stops_route_id_stop_order')
    )
    op.create_index(op.f('ix_shuttle_route_stops_route_id'), 'shuttle_route_stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_shuttle_route_stops_stop_id'), 'shuttle_route_stops', ['stop_id'], unique=False)
    op.create_index(op.f('ix_shuttle_route_stops_stop_order'), 'shuttle_route_stops', ['stop_order'], unique=False)
    op.create_table('shuttle_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('depart_time', sa.Time(), nullable=False),
    sa.Column('arrive_time', sa.Time(), nullable=False),
    sa.Column('service_day_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['shuttle_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_schedules_depart_time'), 'shuttle_schedules', ['depart_time'], unique=False)
    op.create_index(op.f('ix_shuttle_schedules_route_id'), 'shuttle_schedules', ['route_id'], unique=False)
    op.create_index(op.f('ix_shuttle_schedules_service_date'), 'shuttle_schedules', ['service_date'], unique=False)
    op.create_index(op.f('ix_shuttle_schedules_service_day_type'), 'shuttle_schedules', ['service_day_type'], unique=False)
    op.create_index(op.f('ix_shuttle_schedules_status'), 'shuttle_schedules', ['status'], unique=False)
    op.create_table('canteen_menu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stall_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('meal_time', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('spicy_level', sa.Integer(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('available_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stall_id'], ['canteen_stalls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canteen_menu_items_is_available'), 'canteen_menu_items', ['is_available'], unique=False)
    op.create_index(op.f('ix_canteen_menu_items_item_name'), 'canteen_menu_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_canteen_menu_items_meal_time'), 'canteen_menu_items', ['meal_time'], unique=False)
    op.create_index(op.f('ix_canteen_menu_items_stall_id'), 'canteen_menu_items', ['stall_id'], unique=False)
    op.create_table('dorm_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('bed_no', sa.String(length=20), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['dorm_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dorm_assignments_check_in_date'), 'dorm_assignments', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_dorm_assignments_check_out_date'), 'dorm_assignments', ['check_out_date'], unique=False)
    op.create_index(op.f('ix_dorm_assignments_room_id'), 'dorm_assignments', ['room_id'], unique=False)
    op.create_index(op.f('ix_dorm_assignments_status'), 'dorm_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_dorm_assignments_user_id'), 'dorm_assignments', ['user_id'], unique=False)
    op.create_table('dorm_utility_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('utility_type', sa.String(length=20), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['dorm_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'utility_type', name='uq_dorm_utility_accounts_room_id_utility_type')
    )
    op.create_index(op.f('ix_dorm_utility_accounts_account_no'), 'dorm_utility_accounts', ['account_no'], unique=True)
    op.create_index(op.f('ix_dorm_utility_accounts_room_id'), 'dorm_utility_accounts', ['room_id'], unique=False)
    op.create_index(op.f('ix_dorm_utility_accounts_status'), 'dorm_utility_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_dorm_utility_accounts_utility_type'), 'dorm_utility_accounts', ['utility_type'], unique=False)
    op.create_table('student_reward_punishment_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('issuing_unit', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_reward_punishment_records_category'), 'student_reward_punishment_records', ['category'], unique=False)
    op.create_index(op.f('ix_student_reward_punishment_records_level'), 'student_reward_punishment_records', ['level'], unique=False)
    op.create_index(op.f('ix_student_reward_punishment_records_record_date'), 'student_reward_punishment_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_student_reward_punishment_records_record_type'), 'student_reward_punishment_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_student_reward_punishment_records_status'), 'student_reward_punishment_records', ['status'], unique=False)
    op.create_index(op.f('ix_student_reward_punishment_records_user_id'), 'student_reward_punishment_records', ['user_id'], unique=False)
    op.create_table('dorm_utility_usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('usage_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['dorm_utility_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dorm_utility_usage_records_account_id'), 'dorm_utility_usage_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_dorm_utility_usage_records_reading_date'), 'dorm_utility_usage_records', ['reading_date'], unique=False)
    op.alter_column('capability_proposals', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('capability_proposals', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('capability_proposals', 'activation_policy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capability_proposals', 'activation_policy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('capability_proposals', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('capability_proposals', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_dorm_utility_usage_records_reading_date'), table_name='dorm_utility_usage_records')
    op.drop_index(op.f('ix_dorm_utility_usage_records_account_id'), table_name='dorm_utility_usage_records')
    op.drop_table('dorm_utility_usage_records')
    op.drop_index(op.f('ix_student_reward_punishment_records_user_id'), table_name='student_reward_punishment_records')
    op.drop_index(op.f('ix_student_reward_punishment_records_status'), table_name='student_reward_punishment_records')
    op.drop_index(op.f('ix_student_reward_punishment_records_record_type'), table_name='student_reward_punishment_records')
    op.drop_index(op.f('ix_student_reward_punishment_records_record_date'), table_name='student_reward_punishment_records')
    op.drop_index(op.f('ix_student_reward_punishment_records_level'), table_name='student_reward_punishment_records')
    op.drop_index(op.f('ix_student_reward_punishment_records_category'), table_name='student_reward_punishment_records')
    op.drop_table('student_reward_punishment_records')
    op.drop_index(op.f('ix_dorm_utility_accounts_utility_type'), table_name='dorm_utility_accounts')
    op.drop_index(op.f('ix_dorm_utility_accounts_status'), table_name='dorm_utility_accounts')
    op.drop_index(op.f('ix_dorm_utility_accounts_room_id'), table_name='dorm_utility_accounts')
    op.drop_index(op.f('ix_dorm_utility_accounts_account_no'), table_name='dorm_utility_accounts')
    op.drop_table('dorm_utility_accounts')
    op.drop_index(op.f('ix_dorm_assignments_user_id'), table_name='dorm_assignments')
    op.drop_index(op.f('ix_dorm_assignments_status'), table_name='dorm_assignments')
    op.drop_index(op.f('ix_dorm_assignments_room_id'), table_name='dorm_assignments')
    op.drop_index(op.f('ix_dorm_assignments_check_out_date'), table_name='dorm_assignments')
    op.drop_index(op.f('ix_dorm_assignments_check_in_date'), table_name='dorm_assignments')
    op.drop_table('dorm_assignments')
    op.drop_index(op.f('ix_canteen_menu_items_stall_id'), table_name='canteen_menu_items')
    op.drop_index(op.f('ix_canteen_menu_items_meal_time'), table_name='canteen_menu_items')
    op.drop_index(op.f('ix_canteen_menu_items_item_name'), table_name='canteen_menu_items')
    op.drop_index(op.f('ix_canteen_menu_items_is_available'), table_name='canteen_menu_items')
    op.drop_table('canteen_menu_items')
    op.drop_index(op.f('ix_shuttle_schedules_status'), table_name='shuttle_schedules')
    op.drop_index(op.f('ix_shuttle_schedules_service_day_type'), table_name='shuttle_schedules')
    op.drop_index(op.f('ix_shuttle_schedules_service_date'), table_name='shuttle_schedules')
    op.drop_index(op.f('ix_shuttle_schedules_route_id'), table_name='shuttle_schedules')
    op.drop_index(op.f('ix_shuttle_schedules_depart_time'), table_name='shuttle_schedules')
    op.drop_table('shuttle_schedules')
    op.drop_index(op.f('ix_shuttle_route_stops_stop_order'), table_name='shuttle_route_stops')
    op.drop_index(op.f('ix_shuttle_route_stops_stop_id'), table_name='shuttle_route_stops')
    op.drop_index(op.f('ix_shuttle_route_stops_route_id'), table_name='shuttle_route_stops')
    op.drop_table('shuttle_route_stops')
    op.drop_index(op.f('ix_dorm_rooms_status'), table_name='dorm_rooms')
    op.drop_index(op.f('ix_dorm_rooms_room_no'), table_name='dorm_rooms')
    op.drop_index(op.f('ix_dorm_rooms_building_id'), table_name='dorm_rooms')
    op.drop_table('dorm_rooms')
    op.drop_index(op.f('ix_canteen_stalls_status'), table_name='canteen_stalls')
    op.drop_index(op.f('ix_canteen_stalls_stall_code'), table_name='canteen_stalls')
    op.drop_index(op.f('ix_canteen_stalls_category'), table_name='canteen_stalls')
    op.drop_index(op.f('ix_canteen_stalls_canteen_id'), table_name='canteen_stalls')
    op.drop_table('canteen_stalls')
    op.drop_index(op.f('ix_shuttle_stops_stop_name'), table_name='shuttle_stops')
    op.drop_index(op.f('ix_shuttle_stops_stop_code'), table_name='shuttle_stops')
    op.drop_index(op.f('ix_shuttle_stops_status'), table_name='shuttle_stops')
    op.drop_index(op.f('ix_shuttle_stops_campus'), table_name='shuttle_stops')
    op.drop_table('shuttle_stops')
    op.drop_index(op.f('ix_shuttle_routes_status'), table_name='shuttle_routes')
    op.drop_index(op.f('ix_shuttle_routes_start_campus'), table_name='shuttle_routes')
    op.drop_index(op.f('ix_shuttle_routes_route_code'), table_name='shuttle_routes')
    op.drop_index(op.f('ix_shuttle_routes_end_campus'), table_name='shuttle_routes')
    op.drop_table('shuttle_routes')
    op.drop_index(op.f('ix_graduation_requirements_status'), table_name='graduation_requirements')
    op.drop_index(op.f('ix_graduation_requirements_requirement_type'), table_name='graduation_requirements')
    op.drop_index(op.f('ix_graduation_requirements_requirement_code'), table_name='graduation_requirements')
    op.drop_index(op.f('ix_graduation_requirements_major'), table_name='graduation_requirements')
    op.drop_index(op.f('ix_graduation_requirements_grade'), table_name='graduation_requirements')
    op.drop_index(op.f('ix_graduation_requirements_department'), table_name='graduation_requirements')
    op.drop_table('graduation_requirements')
    op.drop_index(op.f('ix_dorm_buildings_status'), table_name='dorm_buildings')
    op.drop_index(op.f('ix_dorm_buildings_gender_rule'), table_name='dorm_buildings')
    op.drop_index(op.f('ix_dorm_buildings_campus'), table_name='dorm_buildings')
    op.drop_index(op.f('ix_dorm_buildings_building_code'), table_name='dorm_buildings')
    op.drop_table('dorm_buildings')
    op.drop_index(op.f('ix_canteens_status'), table_name='canteens')
    op.drop_index(op.f('ix_canteens_canteen_code'), table_name='canteens')
    op.drop_index(op.f('ix_canteens_campus'), table_name='canteens')
    op.drop_table('canteens')
    # ### end Alembic commands ###
