"""add approval

Revision ID: 763903fe7c2c
Revises: 8c1ad5012ff3
Create Date: 2026-03-26 17:47:55.205430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763903fe7c2c'
down_revision: Union[str, None] = '8c1ad5012ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('approval_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_fields_json', sa.JSON(), nullable=False),
    sa.Column('approver_role_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_templates_approval_type'), 'approval_templates', ['approval_type'], unique=False)
    op.create_index(op.f('ix_approval_templates_status'), 'approval_templates', ['status'], unique=False)
    op.create_index(op.f('ix_approval_templates_template_code'), 'approval_templates', ['template_code'], unique=True)
    op.create_table('zero_form_approval_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('approval_type', sa.String(length=50), nullable=False),
    sa.Column('form_data_json', sa.JSON(), nullable=False),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['approval_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zero_form_approval_requests_approval_type'), 'zero_form_approval_requests', ['approval_type'], unique=False)
    op.create_index(op.f('ix_zero_form_approval_requests_approver_user_id'), 'zero_form_approval_requests', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_zero_form_approval_requests_status'), 'zero_form_approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_zero_form_approval_requests_template_id'), 'zero_form_approval_requests', ['template_id'], unique=False)
    op.create_index(op.f('ix_zero_form_approval_requests_user_id'), 'zero_form_approval_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zero_form_approval_requests_user_id'), table_name='zero_form_approval_requests')
    op.drop_index(op.f('ix_zero_form_approval_requests_template_id'), table_name='zero_form_approval_requests')
    op.drop_index(op.f('ix_zero_form_approval_requests_status'), table_name='zero_form_approval_requests')
    op.drop_index(op.f('ix_zero_form_approval_requests_approver_user_id'), table_name='zero_form_approval_requests')
    op.drop_index(op.f('ix_zero_form_approval_requests_approval_type'), table_name='zero_form_approval_requests')
    op.drop_table('zero_form_approval_requests')
    op.drop_index(op.f('ix_approval_templates_template_code'), table_name='approval_templates')
    op.drop_index(op.f('ix_approval_templates_status'), table_name='approval_templates')
    op.drop_index(op.f('ix_approval_templates_approval_type'), table_name='approval_templates')
    op.drop_table('approval_templates')
    # ### end Alembic commands ###
