"""add_schedule_tables

Revision ID: 86c636312931
Revises: 81654004eb2e
Create Date: 2026-03-09 17:55:47.702761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c636312931'
down_revision: Union[str, None] = '81654004eb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_course_code_key', 'courses', type_='unique')
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_index(op.f('ix_courses_semester'), 'courses', ['semester'], unique=False)
    op.create_index(op.f('ix_exam_schedules_course_id'), 'exam_schedules', ['course_id'], unique=False)
    op.drop_constraint('exam_schedules_course_id_fkey', 'exam_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'exam_schedules', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_schedule_entries_course_id'), 'schedule_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_semester'), 'schedule_entries', ['semester'], unique=False)
    op.create_index(op.f('ix_schedule_entries_weekday'), 'schedule_entries', ['weekday'], unique=False)
    op.drop_constraint('schedule_entries_course_id_fkey', 'schedule_entries', type_='foreignkey')
    op.drop_constraint('schedule_entries_user_id_fkey', 'schedule_entries', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_entries', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedule_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_entries', type_='foreignkey')
    op.drop_constraint(None, 'schedule_entries', type_='foreignkey')
    op.create_foreign_key('schedule_entries_user_id_fkey', 'schedule_entries', 'users', ['user_id'], ['id'])
    op.create_foreign_key('schedule_entries_course_id_fkey', 'schedule_entries', 'courses', ['course_id'], ['id'])
    op.drop_index(op.f('ix_schedule_entries_weekday'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_semester'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_course_id'), table_name='schedule_entries')
    op.drop_constraint(None, 'exam_schedules', type_='foreignkey')
    op.create_foreign_key('exam_schedules_course_id_fkey', 'exam_schedules', 'courses', ['course_id'], ['id'])
    op.drop_index(op.f('ix_exam_schedules_course_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_courses_semester'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.create_unique_constraint('courses_course_code_key', 'courses', ['course_code'])
    # ### end Alembic commands ###
