"""add_capability_proposals_table

Revision ID: 8d2cb99bb374
Revises: 763903fe7c2c
Create Date: 2026-04-02 15:37:25.622594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2cb99bb374'
down_revision: Union[str, None] = '763903fe7c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trigger_message', sa.Text(), nullable=False),
    sa.Column('proposal_type', sa.String(length=30), nullable=False),
    sa.Column('capability_name', sa.String(length=100), nullable=False),
    sa.Column('research_summary_json', sa.JSON(), nullable=True),
    sa.Column('proposal_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_proposals_capability_name'), 'capability_proposals', ['capability_name'], unique=False)
    op.create_index(op.f('ix_capability_proposals_proposal_type'), 'capability_proposals', ['proposal_type'], unique=False)
    op.create_index(op.f('ix_capability_proposals_session_id'), 'capability_proposals', ['session_id'], unique=False)
    op.create_index(op.f('ix_capability_proposals_status'), 'capability_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_capability_proposals_user_id'), 'capability_proposals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capability_proposals_user_id'), table_name='capability_proposals')
    op.drop_index(op.f('ix_capability_proposals_status'), table_name='capability_proposals')
    op.drop_index(op.f('ix_capability_proposals_session_id'), table_name='capability_proposals')
    op.drop_index(op.f('ix_capability_proposals_proposal_type'), table_name='capability_proposals')
    op.drop_index(op.f('ix_capability_proposals_capability_name'), table_name='capability_proposals')
    op.drop_table('capability_proposals')
    # ### end Alembic commands ###
