"""add_agent_session_tables

Revision ID: 9084e53aa354
Revises: 1651e1350f50
Create Date: 2026-03-10 15:13:00.196445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9084e53aa354'
down_revision: Union[str, None] = '1651e1350f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_messages_message_type'), 'agent_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_agent_messages_role'), 'agent_messages', ['role'], unique=False)
    op.drop_constraint('agent_messages_session_id_fkey', 'agent_messages', type_='foreignkey')
    op.create_foreign_key(None, 'agent_messages', 'agent_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_agent_sessions_status'), 'agent_sessions', ['status'], unique=False)
    op.drop_constraint('agent_sessions_user_id_fkey', 'agent_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_sessions', type_='foreignkey')
    op.create_foreign_key('agent_sessions_user_id_fkey', 'agent_sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_agent_sessions_status'), table_name='agent_sessions')
    op.drop_constraint(None, 'agent_messages', type_='foreignkey')
    op.create_foreign_key('agent_messages_session_id_fkey', 'agent_messages', 'agent_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_agent_messages_role'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_message_type'), table_name='agent_messages')
    # ### end Alembic commands ###
