"""add tool spec artifact 

Revision ID: b34079d325bd
Revises: e4bcd4c9e28f
Create Date: 2026-04-15 15:48:07.553350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34079d325bd'
down_revision: Union[str, None] = 'e4bcd4c9e28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_plan_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_proposal_id', sa.Integer(), nullable=True),
    sa.Column('capability_name', sa.String(length=100), nullable=False),
    sa.Column('primary_intent', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_proposal_id'], ['capability_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_plan_definitions_capability_name'), 'dynamic_plan_definitions', ['capability_name'], unique=False)
    op.create_index(op.f('ix_dynamic_plan_definitions_primary_intent'), 'dynamic_plan_definitions', ['primary_intent'], unique=True)
    op.create_index(op.f('ix_dynamic_plan_definitions_source_proposal_id'), 'dynamic_plan_definitions', ['source_proposal_id'], unique=False)
    op.create_index(op.f('ix_dynamic_plan_definitions_status'), 'dynamic_plan_definitions', ['status'], unique=False)
    op.create_table('dynamic_tool_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_proposal_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('primary_intent', sa.String(length=100), nullable=False),
    sa.Column('tool_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema_json', sa.JSON(), nullable=False),
    sa.Column('execution_config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_proposal_id'], ['capability_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_tool_definitions_primary_intent'), 'dynamic_tool_definitions', ['primary_intent'], unique=False)
    op.create_index(op.f('ix_dynamic_tool_definitions_source_proposal_id'), 'dynamic_tool_definitions', ['source_proposal_id'], unique=False)
    op.create_index(op.f('ix_dynamic_tool_definitions_status'), 'dynamic_tool_definitions', ['status'], unique=False)
    op.create_index(op.f('ix_dynamic_tool_definitions_tool_name'), 'dynamic_tool_definitions', ['tool_name'], unique=True)
    op.create_index(op.f('ix_dynamic_tool_definitions_tool_type'), 'dynamic_tool_definitions', ['tool_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dynamic_tool_definitions_tool_type'), table_name='dynamic_tool_definitions')
    op.drop_index(op.f('ix_dynamic_tool_definitions_tool_name'), table_name='dynamic_tool_definitions')
    op.drop_index(op.f('ix_dynamic_tool_definitions_status'), table_name='dynamic_tool_definitions')
    op.drop_index(op.f('ix_dynamic_tool_definitions_source_proposal_id'), table_name='dynamic_tool_definitions')
    op.drop_index(op.f('ix_dynamic_tool_definitions_primary_intent'), table_name='dynamic_tool_definitions')
    op.drop_table('dynamic_tool_definitions')
    op.drop_index(op.f('ix_dynamic_plan_definitions_status'), table_name='dynamic_plan_definitions')
    op.drop_index(op.f('ix_dynamic_plan_definitions_source_proposal_id'), table_name='dynamic_plan_definitions')
    op.drop_index(op.f('ix_dynamic_plan_definitions_primary_intent'), table_name='dynamic_plan_definitions')
    op.drop_index(op.f('ix_dynamic_plan_definitions_capability_name'), table_name='dynamic_plan_definitions')
    op.drop_table('dynamic_plan_definitions')
    # ### end Alembic commands ###
