"""add capability proposal governance fields

Revision ID: c07a807f5503
Revises: 8d2cb99bb374
Create Date: 2026-04-14 14:00:49.085572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07a807f5503'
down_revision: Union[str, None] = '8d2cb99bb374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capability_proposals', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('capability_proposals', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('capability_proposals', sa.Column('activation_policy', sa.String(length=20), nullable=True))
    op.add_column('capability_proposals', sa.Column('validation_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_capability_proposals_activation_policy'), 'capability_proposals', ['activation_policy'], unique=False)
    op.create_index(op.f('ix_capability_proposals_risk_level'), 'capability_proposals', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capability_proposals_risk_level'), table_name='capability_proposals')
    op.drop_index(op.f('ix_capability_proposals_activation_policy'), table_name='capability_proposals')
    op.drop_column('capability_proposals', 'validation_reason')
    op.drop_column('capability_proposals', 'activation_policy')
    op.drop_column('capability_proposals', 'risk_level')
    op.drop_column('capability_proposals', 'confidence_score')
    # ### end Alembic commands ###
