"""add_agent_session_memory_table

Revision ID: c51ad01cad88
Revises: 4604e1cd6173
Create Date: 2026-03-12 14:13:25.603535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51ad01cad88'
down_revision: Union[str, None] = '4604e1cd6173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_session_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('current_intent', sa.String(length=50), nullable=True),
    sa.Column('slot_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_session_memories_current_intent'), 'agent_session_memories', ['current_intent'], unique=False)
    op.create_index(op.f('ix_agent_session_memories_session_id'), 'agent_session_memories', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_session_memories_session_id'), table_name='agent_session_memories')
    op.drop_index(op.f('ix_agent_session_memories_current_intent'), table_name='agent_session_memories')
    op.drop_table('agent_session_memories')
    # ### end Alembic commands ###
