"""add tool spec artifact governance fields

Revision ID: e4bcd4c9e28f
Revises: 72e952057a76
Create Date: 2026-04-14 17:43:34.879382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bcd4c9e28f'
down_revision: Union[str, None] = '72e952057a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_spec_artifacts', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('tool_spec_artifacts', sa.Column('implemented_tool_name', sa.String(length=100), nullable=True))
    op.add_column('tool_spec_artifacts', sa.Column('implemented_module_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_spec_artifacts', 'implemented_module_path')
    op.drop_column('tool_spec_artifacts', 'implemented_tool_name')
    op.drop_column('tool_spec_artifacts', 'review_comment')
    # ### end Alembic commands ###
