"""add_resource_booking_tables

Revision ID: f85208557191
Revises: f8b2d4c9a1e0
Create Date: 2026-03-23 15:04:25.534126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85208557191'
down_revision: Union[str, None] = 'f8b2d4c9a1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_code', sa.String(length=50), nullable=False),
    sa.Column('resource_name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_resource_code'), 'resources', ['resource_code'], unique=True)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_table('integrity_score_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrity_score_records_related_id'), 'integrity_score_records', ['related_id'], unique=False)
    op.create_index(op.f('ix_integrity_score_records_related_type'), 'integrity_score_records', ['related_type'], unique=False)
    op.create_index(op.f('ix_integrity_score_records_user_id'), 'integrity_score_records', ['user_id'], unique=False)
    op.create_table('resource_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('booking_type', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_in_deadline', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('no_show_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_bookings_booking_type'), 'resource_bookings', ['booking_type'], unique=False)
    op.create_index(op.f('ix_resource_bookings_end_time'), 'resource_bookings', ['end_time'], unique=False)
    op.create_index(op.f('ix_resource_bookings_resource_id'), 'resource_bookings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_bookings_start_time'), 'resource_bookings', ['start_time'], unique=False)
    op.create_index(op.f('ix_resource_bookings_status'), 'resource_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_resource_bookings_user_id'), 'resource_bookings', ['user_id'], unique=False)
    op.drop_index('ix_policy_handbook_nodes_article_num', table_name='policy_handbook_nodes')
    op.drop_index('ix_policy_handbook_nodes_chapter', table_name='policy_handbook_nodes')
    op.drop_index('ix_policy_handbook_nodes_doc_name', table_name='policy_handbook_nodes')
    op.drop_table('policy_handbook_nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_handbook_nodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chapter', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('article_num', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('article_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('branded_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='policy_handbook_nodes_pkey')
    )
    op.create_index('ix_policy_handbook_nodes_doc_name', 'policy_handbook_nodes', ['doc_name'], unique=False)
    op.create_index('ix_policy_handbook_nodes_chapter', 'policy_handbook_nodes', ['chapter'], unique=False)
    op.create_index('ix_policy_handbook_nodes_article_num', 'policy_handbook_nodes', ['article_num'], unique=False)
    op.drop_index(op.f('ix_resource_bookings_user_id'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_status'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_start_time'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_resource_id'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_end_time'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_booking_type'), table_name='resource_bookings')
    op.drop_table('resource_bookings')
    op.drop_index(op.f('ix_integrity_score_records_user_id'), table_name='integrity_score_records')
    op.drop_index(op.f('ix_integrity_score_records_related_type'), table_name='integrity_score_records')
    op.drop_index(op.f('ix_integrity_score_records_related_id'), table_name='integrity_score_records')
    op.drop_table('integrity_score_records')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_code'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
